config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#landing"
  get "profile", to: "pages#profile"
  get "home", to: "pages#home"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :activities do
    resources :bookings, only: [:new, :create]
    resources :comments, only: [:create]
    resources :chatroom, only: [:create]
  end
  resources :bookings, only: [:edit, :update, :destroy]
  resources :dogs, only: [:show, :create, :new, :edit, :update]
  resources :users, only: [:show, :edit, :update] do
    resources :follows, only: [:create]
  end

  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :photo
  has_one_attached :banner_photo
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable

  has_many :dogs, dependent: :destroy
  has_many :activities, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :sent_follows, class_name: :Follow, foreign_key: :follower_id, dependent: :destroy
  has_many :received_follows, class_name: :Follow, foreign_key: :followee_id, dependent: :destroy
  has_many :that_they_follow, through: :sent_follows, source: :followee, dependent: :destroy
  has_many :that_follow_them, through: :received_follows, source: :follower, dependent: :destroy

  validates :name, presence: true, length: { minimum: 3 }
  validates :location, presence: true
  validates :bio, presence: true, length: { minimum: 10 }
  validates :email, uniqueness: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]

  def show
    @dogs = @user.dogs
    @follow = Follow.find_by(follower_id: current_user, followee_id: @user)
  end

  def edit
  end

  def update
    @user.update(user_params)
    redirect_to profile_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :bio, :location, :photo, :banner_photo)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/views/users/edit.html.erb
<%= simple_form_for(@user) do |f| %>
  <%= f.input :name %>
  <%= f.input :bio %>
  <%= f.input :location %>
  <%= f.input :photo, as: :file  %>
  <%= f.input :banner_photo, as: :file  %>
  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<div class = "profile-container">
  <div class="profile-banner-container">
    <% if @user.banner_photo.attached? %>
      <%= cl_image_tag @user.banner_photo.key, class: "profile-banner-img" %>
    <% end %>
  </div>

    <div class="profile-imgs-names-container">
      <div class="profile-img-container">
        <%# profile user img %>
        <% if @user.photo.attached? %>
          <%= cl_image_tag @user.photo.key, class:"profile-user-img" %>
        <% end %>
        <%# profile user DOG img %>
        <% @user.dogs.each do |dog| %>
          <% if dog.photo.attached? %>
              <%= link_to dog_path(dog) do %>
                <%= cl_image_tag dog.photo.key, crop: :fill, class: "profile-dog-img" %>
            <% end %>
          <% end %>
        <% end %>
      </div>

      <div class ="profile-names-container profile-names-user">
        <h1 class="profile-user-name"><%= @user.name %></h1>
        <% @user.dogs.each do |dog| %>
          <h3 class="profile-dog-name"><%= dog.name %></h3>
        <% end %>
      </div>
    </div>
  </div>

    <div class = "info-cards-container">
      <div class ="index-cards profile-cards">
        <div class = "user-bio-card">
          <h2><strong>Bio:</strong></h2>
          <br>
          <h3><%= @user.bio %></h3>
        </div>
      </div>
      <div class ="index-cards profile-cards">
        <div class = "user-location-card">
          <h2><strong>Location:</strong></h2>
          <br>
          <h3><%= @user.location %></h3>
        </div>
      </div>
    </div>

  <%# ------------------USER FOLLOWS--------------------%>
  <% if !@follow %>

    <%= button_to "Follow this person", user_follows_path(@user), method: :post, class: "profile-buttons follow-button" %>

  <%else%>
    <%= "Following" %>
  <% end %>

  <%# ------------------USER FOLLOWS--------------------%>
</div>