config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#landing"
  get "profile", to: "pages#profile"
  get "home", to: "pages#home"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :activities do
    resources :bookings, only: [:new, :create]
    resources :comments, only: [:create]
    resources :chatroom, only: [:create]
  end
  resources :bookings, only: [:edit, :update, :destroy]
  resources :dogs, only: [:show, :create, :new, :edit, :update]
  resources :users, only: [:show, :edit, :update] do
    resources :follows, only: [:create]
  end

  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/shared/_activity_booking_popup.erb
<!-- Create booking button trigger modal -->
<button type="button" class="btn btn-primary activity-show-btn" data-bs-toggle="modal" data-bs-target="#bookingModal">
  <strong>I want to go!</strong>
</button>

<!-- Booking modal -->
<div class="modal fade booking-popup" id="bookingModal" tabindex="-1" aria-labelledby="bookingModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <button type="button" class="btn btn-primary btns-booking x-btn" data-bs-dismiss="modal" aria-label="Close">X</button>

      <div class="modal-header">
        <h2 class="modal-title booking-popup-titles" id="bookingModalLabel">Do you want to join this activity?</h2>
      </div>
      <div class="modal-body">
        <div class="booking-container">
          <h3 class="booking-popup-titles"> <%= @activity.name %></h3>
          <p> <%= @activity.start_date.strftime("%b %d") %></p>
          <%# <h3><%= @activity.end_date.strftime("End date: %b %d")  </h3> %>
          <p> <%= @activity.start_time.strftime("%H:%M") %> - <%= @activity.end_time.strftime("%H:%M") %> </p>
          <p> &#128205; <%= @activity.location %> </p> <br/>
          <%= simple_form_for [@activity, @booking] do |f| %>
            <h3 class="booking-popup-titles"><%= f.input :number_people, label: "How many people are coming?" %> </h3>
            <h3 class="booking-popup-titles"><%= f.input :number_dogs, label: "How many dogs are coming?" %> </h3>
            <div class="container-btn-form-popup">
              <img src="https://res.cloudinary.com/dbksvt70i/image/upload/v1662369521/descarga_15_otn97c.jpg" alt="Happy dog" class="dog-image-popup">
              <%= f.submit "I want to go!", class: "btn btn-primary booking-btn btns-booking", data: {bs_dismiss: "modal"} %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_activity_chatroom_popup.html.erb
<button type="button" class="btn btn-primary activity-show-btn" data-bs-toggle="modal" data-bs-target="#chatModal"><strong>Go to chat</strong>
</button>

<!-- Modal -->
<div class="modal fade" id="chatModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content probando">
      <div class="modal-header">
        <h4 class="modal-title" id="exampleModalLabel"><strong><%= @activity.name %> chat</h4></strong>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>

      <div class="modal-body">
        <div class="container chatroom dialogos" data-controller="chatroom-subscription"
          data-chatroom-subscription-chatroom-id-value="<%= @chatroom.id %>">

          <div class="messages" class="messages" data-chatroom-subscription-target="messages">
            <% @chatroom.messages.each do |message| %>
              <%= render "messages/message", message: message %>
            <% end %>
          </div>
          <div class="desenlace">
            <%= simple_form_for [@chatroom, @message],
              html: { data: { action: "turbo:submit-end->chatroom-subscription#resetForm" }, class: "d-flex" } do |f|
              %>
              <%= f.input :content,
              label: false,
              placeholder: "Message",
              wrapper_html: {class: "flex-grow-1 user-input-field"}
              %>
              <%= f.submit "Send", class: "btn btn-primary mb-3 chat-button" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_activity_comment_popup.erb
<!-- Add comment button trigger modal -->
<button type="button" class="btn btn-primary activity-show-btn" data-bs-toggle="modal" data-bs-target="#commentModal">
  <strong>Add a comment</strong>
</button>

<!-- Comment modal -->
<div class="modal fade" id="commentModal" tabindex="-1" aria-labelledby="commentModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="commentModalLabel"></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= simple_form_for [@activity, @comment] do |f| %>
          <h3><%= f.input :content, label: "Add your comment:" %> </h3>
          <%= f.submit class: "btn btn-primary btn-lg", data: {bs_dismiss: "modal"}%>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_activity_delete_booking_popup.html.erb
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary activity-show-btn" data-bs-toggle="modal" data-bs-target="#cancelBooking"><strong>Cancel booking</strong>
</button>

<!-- Modal -->
<div class="modal fade" id="cancelBooking" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Are you sure you want to cancel this booking?</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>

      <div class="modal-footer">
        <%= link_to booking_path(@user_booking), data: { turbo: true, "turbo-method": :delete } do %>
          <button type="button" class="btn btn-primary bg-danger">Cancel</button>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_activity_edit_booking_popup.erb
<!-- Edit booking button trigger modal -->
<button type="button" class="btn btn-primary activity-show-btn" data-bs-toggle="modal" data-bs-target="#editBookingModal">
  <strong>Edit my booking</strong>
</button>

<!-- Edit booking modal -->
<div class="modal fade" id="editBookingModal" tabindex="-1" aria-labelledby="editBookingModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <button type="button" class="btn btn-primary btns-booking x-btn" data-bs-dismiss="modal" aria-label="Close">X</button>

      <div class="modal-header">
        <h5 class="modal-title" id="editBookingModalLabel">Edit your activity</h5>
      </div>
      <div class="modal-body">
        <div class="booking-container">
          <h3> <strong><%= @activity.name %> </strong> </h3>
          <h3> <%= @activity.start_date.strftime("Start date: %b %d") %></h3>
          <h3> <%= @activity.start_time.strftime("Start time: %H:%M") %> | <%= @activity.end_time.strftime("End time: %H:%M") %> </h3>
          <h3> &#128205; <%= @activity.location %> </h3>
          <%= simple_form_for @user_booking, data: { turbo:false } do |f| %>
            <h3><%= f.input :number_people %> </h3>
            <%= f.submit class: "btn btn-primary booking-btn btns-booking", data: {bs_dismiss: "modal"}%>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_activity_edit_or_delete_booking_popup.erb
<!-- Edit booking button trigger modal -->
<button type="button" class="btn btn-primary activity-show-btn" data-bs-toggle="modal" data-bs-target="#editBookingModal">
  <strong>Edit my booking</strong>
</button>

<!-- Edit booking modal -->
<div class="modal fade" id="editBookingModal" tabindex="-1" aria-labelledby="editBookingModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="editBookingModalLabel">Edit your activity</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div class="booking-container">
          <h3> <strong><%= @activity.name %> </strong> </h3>
          <h3> <%= @activity.start_date.strftime("Start date: %b %d") %></h3>
          <h3><%= @activity.end_date.strftime("End date: %b %d") %> </h3>
          <h3> <%= @activity.start_time.strftime("Start time: %H:%M") %> | <%= @activity.end_time.strftime("End time: %H:%M") %> </h3>
          <h3> 📍<%= @activity.location %> </h3>
          <%= simple_form_for @user_booking, data: { turbo:false } do |f| %>
            <h3><%= f.input :number_people %> </h3>
            <%= f.submit class: "btn btn-primary", data: {bs_dismiss: "modal"}%>
            <%  %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_delete_activity.html.erb
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary activity-show-btn" data-bs-toggle="modal" data-bs-target="#deleteActivity"><strong>Delete activity</strong>
</button>

<!-- Modal -->
<div class="modal fade" id="deleteActivity" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Are you sure you want to delete the activity?</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>

      <div class="modal-footer">
        <%= link_to activity_path(@activity), data: { turbo: true, "turbo-method": :delete } do %>
          <button type="button" class="btn btn-primary bg-danger">Delete</button>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_edit_activity.html.erb
<!-- Edit booking button trigger modal -->
<button type="button" class="btn btn-primary activity-show-btn" data-bs-toggle="modal" data-bs-target="#editActivityModal">
  <strong>Edit my activity</strong>
</button>

<!-- Edit booking modal -->
<div class="modal fade" id="editActivityModal" tabindex="-1" aria-labelledby="editActivityModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="editActivityModalLabel">Edit or delete your activity</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div class="booking-container">
          <%= simple_form_for @activity, data: { turbo:false } do |f| %>
            <h3><%= f.input :name %> </h3>
            <h3><%= f.input :description %> </h3>
            <h3><%= f.input :location, input_html: {data: {location_autocomplete_target: "location"}, class: "d-none"},
            wrapper_html: {data: {controller: "location-autocomplete", location_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}} %></h3>
            <h3><%= f.input :start_date, as: :string, input_html: {class: "datepicker"}  %></h3>
            <h3><%= f.input :end_date, as: :string, input_html: {class: "datepicker"}  %></h3>
            <h3><%= f.input :start_time %></h3>
            <h3><%= f.input :end_time %></h3>
            <h3><%= f.input :dog_limit %></h3>
            <h3><%= f.input :people_limit %></h3>
            <h3><%= f.input :price %></h3>
            <h3><%= f.input :photo, as: :file %></h3>
            <%= f.submit class: "btn btn-primary", data: {bs_dismiss: "modal"}%>
            <%  %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_map.html.erb
<%#-------MAP------%>
<div class = "map-container"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>
<%#-------MAP------%>

app/views/shared/_navbar.html.erb
<div class="main-navbar-container" data-controller="navbar">

  <%= link_to home_path do %>
    <div class="logo-container">
        <img src="https://res.cloudinary.com/mariacend1910/image/upload/v1662368952/Roby_dog_uezddt.svg" class="logo" alt="">
    </div>
  <% end %>

  <div class="menu-icon" data-action="click->navbar#handleClick" data-navbar-target="icon">
    <i class="fa-solid fa-bars" data-navbar-target="font" data-action="click->navbar#changeIcon"></i>
  </div>

  <ul class="nav-menu" data-navbar-target="list">
    <% if user_signed_in? %>

      <li class="">
        <%= link_to home_path, class: "navbar-logo" do %>
          <img class="navbar-logo" src="https://res.cloudinary.com/mariacend1910/image/upload/v1662369317/Roby_white_zmjqae.svg" alt="">
        <% end %>
      </li>

      <li class="">
        <%= link_to profile_path, class: "black" do %>
          <button class="navbar-button">My Profile</button>
        <% end %>
      </li>

      <li class="">
        <%= link_to activities_path, class: "black" do %>
          <button class="navbar-button">Find an activity</button>
        <% end %>
      </li>

      <li class="">
        <%= link_to new_activity_path, class: "black" do %>
          <button class="navbar-button">Create a new activity</button>
        <% end %>
      </li>

      <li class="">
        <%= link_to destroy_user_session_path, data: {turbo_method: :delete}, class: "black"  do %>
          <button class="navbar-button">Log out</button>
        <% end %>
      </li>

    <% else %>
      <li class="">
        <%= link_to new_user_session_path, class: "black" do %>
          <button class="navbar-button">Login</button>
        <% end %>
      </li>
    <% end %>

    <div class="navbar-footer">
      ❤️ Made with love by: ❤️ <br>
      <a href="https://www.linkedin.com/in/gloria-font-8b084824b/" target="_blank">Gloria</a>,
      <a href="https://www.linkedin.com/in/mariajesuscendoya/" target="_blank">Maria</a>,
      <a href="https://www.linkedin.com/in/grace-lavender/" target="_blank">Grace</a>,
      <a href="https://www.linkedin.com/in/daniel-ramiro-lanz/" target="_blank">Dani</a>
      and <a href="https://www.linkedin.com/in/felipe-fischel/" target="_blank">Felipe</a>.
    </div>
  </ul>

</div>