config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#landing"
  get "profile", to: "pages#profile"
  get "home", to: "pages#home"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :activities do
    resources :bookings, only: [:new, :create]
    resources :comments, only: [:create]
    resources :chatroom, only: [:create]
  end
  resources :bookings, only: [:edit, :update, :destroy]
  resources :dogs, only: [:show, :create, :new, :edit, :update]
  resources :users, only: [:show, :edit, :update] do
    resources :follows, only: [:create]
  end

  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/pages/home.html.erb
<div class = "container-home">

  <div class = "animation">
  </div>

  <div class="home-search">
    <h2 id="search-title">Find new activities</h2>
      <div class = "search-form">
        <%= form_with url: activities_path, method: :get, class: "search-bar d-flex" do %>
          <%= text_field_tag :query,
          params[:query],
          class: "search-form-bar",
          placeholder: "Find an activity" %>
          <%= submit_tag "Search", class: "search-button" %>
        <% end %>
      </div>
  </div>

  <%#-------MAP------%>
  <div class ="map-home-container">
    <%= render "shared/map" %>
  </div>
  <%#-------MAP------%>

  <div class ="activities-carousel-container">
    <h2 class = "activies-carousel-title">Activities you might like:</h2>
    <div class = "activities-home-slider">
      <% @activities.slice(0,6).each do |activity| %>
        <%= link_to activity_path(activity) do %>
          <div class="activity-home-card">
            <%# <div class="activities-card-image"> %>
            <% if activity.photo.attached? %>
              <%= cl_image_tag activity.photo.key, class:"activities-card-image"%>
            <% else %>
              <img class="activities-card-image" src="https://www.helpguide.org/wp-content/uploads/dog-owner-walking-on-trail.jpg" alt="">
            <% end %>
            <%# </div> %>
            <div class="activity-card-title">
              <h3> <strong><%= activity.name %> </strong></h3>
              <p class="home-location-text"><%= activity.location %></p>
            </div>
          </div>
        <%end%>
      <%end%>
    </div>
  </div>
  <div class="general-chat-home">

  </div>

  <h2 class = "categories-cards-title"><strong>Top Categories for you:</strong></h2>
  <div class = "categories-container">
    <% Category.first(4).each do |category|%>
      <%= link_to activities_path(category:category.id) do %>
        <div class = "categories-card-homepage">
          <%= cl_image_tag category.photo.key, class:"category-card-image"%>
          <div class="category-card-title">
            <h3><strong class="white-text"><%= category.name %></strong></h3>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/pages/landing.html.erb
  <div class = "landing-container">
    <div class = "landing-page-content">
      <img class ="robyletters" src="https://res.cloudinary.com/mariacend1910/image/upload/v1662368379/Roby_logo_2_vccltl.svg">
    <div data-controller="bark" class ="robycircle" id="audio">
      <audio
        src="https://res.cloudinary.com/dfbhewkkh/video/upload/v1662641354/mixkit-dog-barking-twice-1_online-audio-converter.com_i9gwal.mp3"
      ></audio>
    </div>

    <audio
      id="audio"
        src="https://res.cloudinary.com/dfbhewkkh/video/upload/v1662641354/mixkit-dog-barking-twice-1_online-audio-converter.com_i9gwal.mp3"
    ></audio>

    <%= link_to home_path do %>
      <h1 class ="enter">Tap to enter</h1>
    <% end %>
    </div>
  </div>

app/views/pages/landingpage.html.erb
<h1>this is the landing page</h1>

app/views/pages/profile.html.erb
<div class = "profile-container">
  <div class="profile-banner-container">
    <% if current_user.banner_photo.attached? %>
      <%= cl_image_tag current_user.banner_photo.key, class: "profile-banner-img" %>
    <% end %>
  </div>

  <div class="profile-imgs-names-container">
    <%# profile user img %>
    <% if current_user.photo.attached? %>
      <%= cl_image_tag current_user.photo.key, class:"profile-user-img" %>
    <% end %>
    <%# profile user DOG img %>
    <% current_user.dogs.each do |dog| %>
      <% if dog.photo.attached? %>
        <%= link_to dog_path(dog) do %>
          <%= cl_image_tag dog.photo.key, crop: :fill, class: "profile-dog-img" %>
        <% end %>
      <% end %>
    <% end %>
  </div>

  <div class ="profile-names-container">
    <h1 class="profile-user-name"><%= current_user.name %></h1>
    <% current_user.dogs.each do |dog| %>
      <h3 class="profile-dog-name"><%= dog.name %></h3>
    <% end %>
  </div>

  <div class = "profile-btns-container">
    <%= link_to "Edit Profile", edit_user_path(current_user), class: "btn btn-primary btn-sm profile-buttons" %>
    <%= link_to "Add Dog", new_dog_path, class: "btn btn-primary btn-sm profile-buttons" %>
  </div>

  <div class = "info-cards-container">
    <div class ="index-cards profile-cards">
      <div class = "user-bio-card">
        <h2><strong>Bio:</strong></h2>
        <br>
        <h3><%= current_user.bio %></h3>
      </div>
    </div>
    <div class ="index-cards profile-cards">
      <div class = "user-location-card">
        <h2><strong>Location:</strong></h2>
        <br>
        <h3><%= current_user.location %></h3>
      </div>
    </div>
  </div>

  <div class = "friends-container">
    <h2><strong>Friends:</strong></h2>
    <div class = "friends-container-imgs">
      <% current_user.sent_follows.each do |followee| %>
      <% user = User.find_by(id:followee.followee_id) %>
        <% if user.photo.attached? %>
          <%= link_to user_path(user) do %>
            <%= cl_image_tag user.photo.key, class:"friends-pic" %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>

  <%= link_to "Create New Activity", new_activity_path, class: "btn btn-primary btn-sm profile-buttons" %>

  <div>
    <h2 class = "activity-profile-titles"><strong>Attending activities:</strong></h2>
    <% if @user_booking.empty? %>
      <p>You are not attending any activities.</p>
    <% else %>
      <div class = "profile-activities-container">
        <% @user_booking.each do |booking|%>
          <%= link_to activity_path(booking.activity_id) do %>
            <div class= "profile-activities-cards">
              <% if booking.activity.photo.attached? %>
                <%= cl_image_tag booking.activity.photo.key, class:"img-card-profile"%>
                <h3><strong><%= booking.activity.name %></strong></h3>
                <p><%= booking.activity.start_date.strftime("%d/%b/%y") %></p>
              <% else %>
                <img class="index-image-cards" src="https://www.helpguide.org/wp-content/uploads/dog-owner-walking-on-trail.jpg" alt="">
                <h3><strong><%= booking.activity.name %></strong></h3>
                <br>
                <p><%= booking.activity.start_date.strftime("%d/%b/%y") %></p>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>

    <h2 class = "activity-profile-titles"><strong> My activities:</strong></h2>
    <% if @user_activities.empty? %>
      <p>You have not created any activities.</p>
    <% else %>
      <div class = "activities-created-container">
        <% @user_activities.each do |activity|%>
          <%= link_to activity_path(activity) do %>
            <div class= "profile-activities-cards">
              <% if activity.photo.attached? %>
                <%= cl_image_tag activity.photo.key, class:"img-card-profile"%>
              <% else %>
              <img class ="img-card-profile" src="https://img.freepik.com/free-photo/side-view-owner-walking-with-dog_23-2149457838.jpg?w=2000">
              <% end %>
                <h3><strong><%= activity.name %></strong></h3>
                <p><%= activity.start_date.strftime("%b %d") %></p>
            </div>
          <% end %>
        <% end %>
      </div>
    <% end %>
</div>